name: Update README with version info

on:
  push:
    branches:
      - main
      - dev

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version, branch and commit
        id: vars
        run: |
          VERSION=$(node -p "require('./package.json').version")
          BRANCH=${GITHUB_REF##*/}
          COMMIT=$(git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          sed -i "s|<!--VERSION-->.*<!--/VERSION-->|<!--VERSION-->Versión actual: ${{ steps.vars.outputs.branch }} v${{ steps.vars.outputs.version }} (commit ${{ steps.vars.outputs.commit }})<!--/VERSION-->|" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "chore: update README with version info [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF##*/}
