name: Update README with version

on:
  push:
    tags:
      - 'v*'   # solo se dispara cuando hacés push de un tag tipo v1.2.3

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update README.md
        run: |
            sed -i "s/<!--VERSION-->.*<!--\/VERSION-->/<!--VERSION-->Versión actual: ${{ steps.ver.outputs.version }}<!--\/VERSION-->/" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README with version $VERSION" || echo "No changes"
          git push
