name: Update README with version

on:
  push:
    tags:
      - 'v*.*.*'   # solo se dispara cuando hacés push de un tag tipo v1.2.3
  workflow_dispatch:   # permite correrlo manualmente desde la UI (útil para pruebas)
    inputs:
      version:
        description: 'Opcional: versión a fijar (ej: v1.2.3). Si se deja vacío usa el tag que disparó el run.'
        required: false

permissions:
  contents: write  # necesario para hacer push al repo

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            persist-credentials: true # para poder pushear después

      - name: Determine version 
        id: ver
        run: |
            if [[ "GITHUB_REF" == "refs/tags/"* ]]; then
              TAG=${GITHUB_REF#refs/tags/}
              echo "version=$TAG" >> $GITHUB_OUTPUT
            elif [[ -n "${{ github.event.inputs.version }}" ]]; then
              echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            else
              echo "No version found from tag or input. Exiting."
              echo "version=UNSET" >> $GITHUB_OUTPUT
            fi

      - name: Show chosen version (debug)
        run: echo "Version to set = ${{ steps.ver.outputs.version }}"

      - name: Update README VERSION block
        run: |
          set -e
          sed -i "s/<!--VERSION-->.*<!--\/VERSION-->/<!--VERSION-->Versión actual: ${{ steps.ver.outputs.version }}<!--\/VERSION-->/" README.md
          git status --porcelain
          git add README.md
          git commit -m "chore: update README version to ${{ steps.ver.outputs.version }}" || echo "No changes to commit"
          git push